# Generated by Django 5.2.17 on 2026-09-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='material_pdf',
            field=models.FileField(blank=True, null=True, upload_to='module_materials/'),
        ),
    ]
